### ISSUE TITLE
Include dataset names in log messages

### ISSUE THREAD

**Issue by stuarteberg** [connectome-neuprint/neuPrintHTTP#51]
In the log, the neuprint dataset (hemibrain vs vnc) isn't mentioned.  It would be nice to include that, so we know which datasets have been accessed most heavily.

**Comment by stuarteberg** [comment]
@DocSavage Is this something you could do?  We'll also be making other minor updates to neuprintHTTP soon.

**Comment by neomorphic** [comment]
duplicate of #63
